version: '3'
services:
  home-assistant:
    image: 'homeassistant/home-assistant:2022.2'
    ports:
      - "8123:8123"
    restart: unless-stopped
    volumes:
      - '/Users/benjaminengel/Documents/homeassistant:/config'
      - '/etc/localtime:/etc/localtime:ro'
    privileged: true
